### ISSUE TITLE
可以帮忙删除一下这个issuse吗？看着有点碍眼。

### ISSUE THREAD

**Issue by cyj98** [medivhzhan/miniapp#22]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1&index=1

**Comment by medivhzhan** [comment]
准备把支付相关单独分离成一个包，可是最近一直都比较忙。😂

**Comment by cyj98** [comment]
才发现小城刷不支持沙箱环境

**Comment by cyj98** [comment]
可以帮忙删除一下这个issuse吗？在历史活动看着有点碍眼。
