### ISSUE TITLE
小程序下发客服消息错误

### ISSUE THREAD

**Issue by yang3259** [medivhzhan/miniapp#42]
安卓正常，ios提示：小程序提供的服务出现故障 请稍后再试

**Comment by yang3259** [comment]
问题原因：
/medivhzhan/weapp/v2@v2.2.1/server.go  
Line:566

![image](https://user-images.githubusercontent.com/22877816/88471833-0bbcca80-cf40-11ea-8730-9d51e9bf5ba0.png)
https://developers.weixin.qq.com/miniprogram/dev/framework/server-ability/message-push.html

**Comment by medivhzhan** [comment]
对于没有返回的数据，已经西东返回[success](https://github.com/medivhzhan/miniapp/blob/master/server.go#L572)了，
可以再把你的问题描述清楚点吗？谢谢 ：）

**Comment by im-oss** [comment]
我也遇到该问题，在ios设备发送客服消息，会进入 [https://github.com/medivhzhan/miniapp/blob/master/server.go#L566](raw) 
在安卓设备正常

**Comment by medivhzhan** [comment]
已经修复，谢谢各位 ：）
