### ISSUE TITLE
在ocr中各api添加XXXByReader接口

### ISSUE THREAD

**Issue by ccmouse2** [medivhzhan/miniapp#43]
现有的XXX接口（比如DriverLicense)接收一个filename参数。这规定了服务器必须从本地路径获取图片。而这个图片具体存放的方式是根据服务器及存储设计而变化的，很可能不在本地服务器。考虑到此处图片非常敏感，也很可能没有一个安全的外部URL可以供微信服务器访问到。
建议在api设计上，最大程度与服务器的存储设计以及安全考量进行解藕，提议加入：
XXXByData接口，定义：（以DriverLicense举例）
`func DriverLicenseByReader(token string, r io.Reader) (*DrivingLicenseResponse, error)`

**Comment by medivhzhan** [comment]
DriverLicenseByURL 这个接口可以满足不呢？
