### ISSUE TITLE
直播组件live.go 返回类型和官方不一样  json: cannot unmarshal string into Go struct field LiveRoomItem.room_info.feeds_img of type int

### ISSUE THREAD

**Issue by LOFTERART** [medivhzhan/miniapp#51]
"feeds_img": "XXX"			// 官方收录封面

live.go定义的struct 为int

解析报错  json: cannot unmarshal string into Go struct field LiveRoomItem.room_info.feeds_img of type int

**Comment by medivhzhan** [comment]
谢谢，最新版本已经修复；
