### ISSUE TITLE
SubscribeMessage 发送订阅消息，Data 类型是不是错了

### ISSUE THREAD

**Issue by zzir** [medivhzhan/miniapp#54]
文档里的 SubscribeMessageData{} 结构没有找到，当把消息模版参数转换为字符给 data 时，消息发送失败

**Comment by detailid** [comment]
TemplateID 也错了 invalid template_id

**Comment by medivhzhan** [comment]
用map把内容Marshal为JSON字符串再赋值给Data

**Comment by medivhzhan** [comment]
然后确认的传入的数据都是正确的

**Comment by medivhzhan** [comment]
然后确认传入的模板相关数据都是正确的
