### ISSUE TITLE
处理支付结果通知如何验证签名

### ISSUE THREAD

**Issue by shiruitao** [medivhzhan/miniapp#9]
fmt.Printf("%#v", ntf)，ntf 里面的 Sign 需要哪个字段去签名对比

**Comment by medivhzhan** [comment]
@shiruitao 调用支付时生成sign的那些数据，可以看下[微信官方支付文档](https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3)
